# Set your theme here
theme: hugo-tufte
# Remove this if your site folder is not inside the theme folder
themesDir: "./themes"
# The language of your website (see https://www.andiamo.co.uk/resources/iso-language-codes/ for reference)
languageCode: en-US
# If you write Chinese, Japanese or Korean, this helps with word counting
hasCJKLanguage: true
# The url of your website
#baseurl: "http://localhost:1313/"
baseurl: "https://github.com/ghartsel/blog"
#baseurl: "https://hugo-tufte.netlify.app/"
# The title of your website (shown on all the pages)
title: "Î»Î¹Ï„ÏŒÏ„Î·Ï‚"
canonifyurls: true
# Number of posts per page on the home page
#paginate: 5
pagination:
  disableAliases: false
  pagerSize: 5
  path: page

# Only modify the following if you know what you are doing
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: true

params:
  # Subtitle of the website
  subtitle: ""
  favicon: "./favicon.ico"
  touchicon: "./touch-icon.png"
  # Dark code highlighting
  codeblocksdark: false
  # Customize the indicator for margin notes
  # Some suggestions: âŠ•, ğŸ’¬, ğŸ’­, ğŸ“‘, ğŸ·, âœ, ğŸ’¡, ğŸ§, ğŸ“, ğŸ“Œ
  marginNoteInd: "âŠ•"
  # Your name or the name of you company
  # copyright: Copyright 2023
  # copyrightHolder: Copyright Holder
  # Show the "Powered by Hugo-Tufte and Hugo."
  showPoweredBy: false
  # Site wide kill switch for date in pages
  hidedate: false
  # Site wide kill switch for post summary on home page
  showSummary: true
  # Site wide kill switch for LaTeX support
  math: true
  KaTeXVersion: 0.16.4
  KaTeXCDN: "//cdn.jsdelivr.net/npm"
  # #### Control style flavours of the website
  # Use upright & sans-serif font for subtitles
  sansSubtitle: false
  # Make the page centred in screen
  centerArticle: false
  # ######## Common social website links, please comment the unused ones.
  # (if your favorite one is not in the list, please head to the footer menu below and add an entry)
  # Please note that some of the value below are only provided as an exemple, perhaps the computed isn't valid
  # github: slashformotion
  # gitlab: slashformotion
  # linkedin: <insert_here>
  # twitter: slashformotion
  # patreon: ''
  # youtube: user/ChromeDevelopers # check the end of your youtube url https://www.youtube.com/<copy_this>
  # medium: slashformotion
  # reddit: Slashformotion
  # stackoverflow: 16609732/slashformotion
  # instagram: google
  # mastodon: instance.url/@username
  # orcid: 0000-0003-0634-3275
  # google_scholar: jm5QaHkAAAAJ

taxonomies:
  category: categories
  series: series
  tag: tags

# -----------------------------------------------------------------------
# Navigation menu
# -----------------------------------------------------------------------
# -----------------------------------------------------------------------
# FOOTER MENU
# If you need to add custom links to you footer: put them here.
# -----------------------------------------------------------------------
  # footer:
  #   - name: Custom footer link
  #     weight: -90
  #     identifier: custom_link
  #     url: 'https://example.com'
